[server]
runOnSave = true
enableStaticServing = true

[[theme.fontFaces]]
family = "Inter"
url = "app/static/font/Inter-VariableFont.ttf"
weight = 500


[[theme.fontFaces]]
family = "Inter Black"
url = "app/static/font/Inter-VariableFont.ttf"
weight = 900

[theme]
font = "Inter"
headingFont = "Inter Black"
primaryColor = "#2BB17A"